In [2]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv("..\data\\raw\\remote_work_productivity.csv")
df.head()

,Employee_ID,Age,Years_Experience,WFH_Days_Per_Week,Gender,Education_Level,Marital_Status,Has_Children,Location_Type,Department,...,Quality_Score,Innovation_Score,Efficiency_Rating,Meetings_Per_Week,Commute_Time_Minutes,Job_Satisfaction,Stress_Level,Work_Life_Balance,Survey_Date,Response_Quality
0,EMP0001,39,10,2,Female,Associate Degree,Married,Yes,Urban,Product,...,58.1,52.1,72.1,4,48,55.9,6,8,2024-04-05,Medium
1,EMP0002,33,4,5,Female,Master Degree,Married,No,Urban,Customer Success,...,93.3,77.9,89.5,12,0,96.1,3,8,2024-01-29,High
2,EMP0003,40,3,3,Male,PhD,Single,Yes,Rural,Operations,...,84.7,63.2,95.0,15,24,90.4,5,6,2024-01-18,High
3,EMP0004,48,14,3,Male,Bachelor Degree,Married,Yes,Urban,Finance,...,67.8,82.5,95.0,8,8,100.0,10,5,2024-04-18,High
4,EMP0005,32,6,5,Male,High School,Divorced,Yes,Rural,Engineering,...,86.4,67.5,95.0,10,0,100.0,3,4,2024-02-19,High

In [22]:
df.corr(numeric_only=True)

,Age,Years_Experience,WFH_Days_Per_Week,Work_Hours_Per_Week,Productivity_Score,Task_Completion_Rate,Quality_Score,Innovation_Score,Efficiency_Rating,Meetings_Per_Week,Commute_Time_Minutes,Job_Satisfaction,Stress_Level,Work_Life_Balance
Age,1.000000,0.663899,0.016873,-0.022432,0.265518,0.243893,0.259228,0.181052,0.238945,0.038832,-0.030135,0.135860,-0.013226,-0.034744
Years_Experience,0.663899,1.000000,-0.003754,0.007720,0.253481,0.218199,0.257541,0.248338,0.211528,0.040026,0.004223,0.138811,-0.019017,-0.035139
WFH_Days_Per_Week,0.016873,-0.003754,1.000000,0.003936,0.018172,0.042617,0.023216,0.007789,0.012685,-0.027806,-0.437151,-0.001237,-0.020237,-0.034015
Work_Hours_Per_Week,-0.022432,0.007720,0.003936,1.000000,-0.030801,-0.017614,-0.036716,-0.007576,-0.092753,0.015941,0.023970,-0.038912,-0.007009,0.040914
Productivity_Score,0.265518,0.253481,0.018172,-0.030801,1.000000,0.884187,0.917980,0.782948,0.838087,-0.004250,-0.031447,0.513332,-0.015355,0.029674
Task_Completion_Rate,0.243893,0.218199,0.042617,-0.017614,0.884187,1.000000,0.811034,0.686079,0.733153,0.016871,-0.052445,0.444480,-0.030967,0.024061
Quality_Score,0.259228,0.257541,0.023216,-0.036716,0.917980,0.811034,1.000000,0.734091,0.771892,-0.007149,-0.036618,0.472340,0.001650,0.027952
Innovation_Score,0.181052,0.248338,0.007789,-0.007576,0.782948,0.686079,0.734091,1.000000,0.652936,-0.000133,-0.048951,0.443077,0.001442,0.023420
Efficiency_Rating,0.238945,0.211528,0.012685,-0.092753,0.838087,0.733153,0.771892,0.652936,1.000000,-0.011763,-0.034454,0.488701,-0.014030,0.025397
Meetings_Per_Week,0.038832,0.040026,-0.027806,0.015941,-0.004250,0.016871,-0.007149,-0.000133,-0.011763,1.000000,0.023277,0.005683,-0.020908,0.032049
Commute_Time_Minutes,-0.030135,0.004223,-0.437151,0.023970,-0.031447,-0.052445,-0.036618,-0.048951,-0.034454,0.023277,1.000000,-0.029735,-0.009307,-0.011542
Job_Satisfaction,0.135860,0.138811,-0.001237,-0.038912,0.513332,0.444480,0.472340,0.443077,0.488701,0.005683,-0.029735,1.000000,-0.014740,0.009763
Stress_Level,-0.013226,-0.019017,-0.020237,-0.007009,-0.015355,-0.030967,0.001650,0.001442,-0.014030,-0.020908,-0.009307,-0.014740,1.000000,-0.003941
Work_Life_Balance,-0.034744,-0.035139,-0.034015,0.040914,0.029674,0.024061,0.027952,0.023420,0.025397,0.032049,-0.011542,0.009763,-0.003941,1.000000